# Generated by Django 4.2.5 on 2023-09-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Worker',
        ),
    ]
