# Generated by Django 4.2.5 on 2023-09-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0002_rename_order_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='second_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_code',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vb_app.position'),
        ),
    ]
