# Generated by Django 4.2.5 on 2023-09-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0003_position_remove_worker_name_remove_worker_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
