# Generated by Django 4.2.5 on 2023-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0004_alter_worker_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
